security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
coa:
  host: ${ORDS_HOST}
  username: ${ORDS_USERNAME}
  password: ${ORDS_PASSWORD}
  object-store-psw: ${OBJ_STORE_PSW}
  object-store-app-id: ${OBJ_STORE_APP_ID}
  object-store-db-id: ${OBJ_STORE_DB_ID}
  object-store-username: ${OBJ_STORE_USER}
  object-store-version: ${OBJ_STORE_VERSION}
  object-store-ticket-lifetime: ${OBJ_STORE_TICKET_LIFETIME}
management:
  trace:
    http:
      include: TIME_TAKEN,RESPONSE_HEADERS
  endpoints:
    web:
      exposure:
        include: httptrace,metrics,prometheus,health

